### ISSUE TITLE
Resize Titles: What's the first number?

### ISSUE THREAD

**Issue by Ypot** [kuanyui/moe-theme.el#101]
Hi
Thanks a lot for your theme. It's my favourite one.

The first number seems to not have effect on font size:
```
;; MOE's
(require 'moe-theme)
(setq moe-theme-resize-org-title '(5.0 1.4 1.2 1.2 1.2 1.2 1.2 1.2 1.2))
(moe-dark)
```

**1.4** is the size of the first heading.
**5.0** I don't know what it affects to.

**Comment by kuanyui** [comment]
It affects `#+TITLE:`

Issue closed.

2019年9月13日(金) 20:21 Ypot <notifications@github.com>:

**Comment by kuanyui** [comment]
closed.

2019年9月13日(金) 20:29 hiromi ono <azazabc123@gmail.com>:
