### ISSUE TITLE
Background is not black

### ISSUE THREAD

**Issue by Ypot** [kuanyui/moe-theme.el#105]
I don't know if it is correct, but the background in the dark theme is dark, but not completely black (#00000). For example, hidden *** appear like grey if I set them black.
Can this be corrected manually at least?

**Comment by kuanyui** [comment]
This is in purpose.

> Can this be corrected manually at least?

https://stackoverflow.com/questions/11418648/how-to-set-default-emacs-background-and-foreground-colors
