### ISSUE TITLE
Using the cl builtin emacs package which is deprecated in emacs 27

### ISSUE THREAD

**Issue by zakariaz** [kuanyui/moe-theme.el#111]
Hi,

The theme is using the `cl` builtin package which is deprecated. I think emacs is going to replace it whit `cl-lib`

It will be nice to update the package since every time i open emacs i see a warning in my echo area about `cl` deprecation.

Thank you for the amazing work you've done. moe theme is my favorite theme

**Comment by zakariaz** [comment]
I submitted a PR #113 to suppress the warning. it is basically requiring `cl-lib` instead of `cl`

**Comment by kuanyui** [comment]
Has this issue still existed?

**Comment by zakariaz** [comment]
Sorry i forgot to close the issue.
