### ISSUE TITLE
moe-theme-set-color is broken

### ISSUE THREAD

**Issue by gmmeyer** [kuanyui/moe-theme.el#112]
When I updated moe theme it now tells me that the symbol's function definition is void. It says that this is the preferred way to continue doing it on the readme on the front page. But the function does appear to be gone in the repo (at least from searching).

From looking through the git log I cannot tell when it disappeared, so I dunno what happened here. But if it's no longer there it should be at least removed from the readme

Thanks for all your work on this great project btw! I really appreciate it!

**Comment by kuanyui** [comment]
Hmmm... Sorry I also forgot.
Are you using master or dev branch? In fact I currently use dev personally, and is considering to make it as main branch to prevent someone else miata mistakenly use it...

**Comment by kuanyui** [comment]
Function 
`moe-theme-select-color`

Or variable
```
(defvar moe-theme-mode-line-color 'blue
  "Default is 'blue.
If nil, no background color.
Available choices: 'blue, 'cyan', 'green, 'magenta, 'red, 'orange, 'yellow, 'purple, 'b/w")
```
