### ISSUE TITLE
'font-lock-comment-delimiter-face' looks stranges in moe-theme

### ISSUE THREAD

**Issue by LimingFang** [kuanyui/moe-theme.el#117]
When using moe-theme, the code comment look somewhat strange, not only c++,elisp..The text are surrounded by some box with different color:
![image](https://user-images.githubusercontent.com/28479651/141884270-926b13e7-6032-450e-8483-6b6a007178d3.png)
![image](https://user-images.githubusercontent.com/28479651/141884322-8c43cdc1-77c1-44a6-b6aa-e040ed4e35ce.png)  
I don't want such box.....And here is the config of 'font-lock-comment-delimiter-face' :
![image](https://user-images.githubusercontent.com/28479651/141884238-356b0a6e-924c-4117-a295-b517870e98c4.png)
If more info is needed, just point out.
Thanks for your theme, it looks nice.

**Comment by kuanyui** [comment]
I guess this is because you have applied another theme before (or after) applying moe-theme, and the theme had overwritten `font-lock-comment-delimiter-face`. In Emacs, themes can be "mixed" by user, which the latter applied one will overwrite the previous one.

In moe-theme, I didn't specify the background color for it:

```lisp
   `(font-lock-comment-delimiter-face    ((,class (:background nil :foreground ,moe-dark-comment-delimiter        :slant italic))))
```
And looks correctly in my Emacs:
![Screenshot_20211116_115842](https://user-images.githubusercontent.com/1370070/141898850-c1a59ea2-3051-421a-8d77-7dd19aa181b2.png)

**Comment by LimingFang** [comment]
@kuanyui Sorry to disturb you again... I use moe-theme in emacs APP, it works fine, but problem occurs when using emacs inside terminal. I wonder if it's terminal's fault? But other theme don't have such problem, sad.

**Comment by LimingFang** [comment]
I thought it's termianl's fault..   
My emacs app works fine but moe-theme doesn't work well under emacs inside terminal ...
However, other themes don't exist such problem..

**Comment by kuanyui** [comment]
Yes, if I remember correctly it's indeed possible. Under some terminal environment, the italic will be rendered as inverted color.

Please check your `$TERM`. I use `export TERM=xterm-256color` and looks correctly.

**Comment by LimingFang** [comment]
Strangely, `$TERM` is already `xterm-256color`..
Anyway, i could just use moe-theme in Emacs App. As for terminal, let it go.

**Comment by kuanyui** [comment]
Don't know what kind of terminal emulator you are using.

I've ever used under 
- Konsole (xterm-256color)
- Konsole (xterm-256color) + tmux (with `~/.tmux.conf` `set -g default-terminal "xterm-256color"`)
- macOS built-in Terminal.app (I forgot it was `xterm-256color` or `screen-256color`... it was years ago.)

I set the envvar in Konsole's setting page:
![Screenshot_20211122_153010](https://user-images.githubusercontent.com/1370070/142820943-c8f96ef8-c298-4d64-9488-77ead5a93787.png)

This is result.
![Screenshot_20211122_152318](https://user-images.githubusercontent.com/1370070/142820958-0b73f7cc-bd58-4cd1-8f6e-25f449186bcc.png)
![Screenshot_20211122_152557](https://user-images.githubusercontent.com/1370070/142820962-6b51f7cf-b88b-4b2a-92f6-84fe95bb65e8.png)

------

BTW, there's another possible reason, is that the font you're using doesn't containing italic. This could happened on some distro such as openSUSE.

Create a file `/etc/fonts/local.conf`:
```xml
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
 <alias binding="strong">
  <family>monospace</family>
  <prefer>
   <family>DejaVu Sans Mono</family>
   <family>Ubuntu Mono</family>
   <family>Droid Sans Mono</family>
   <family>Noto Mono</family>
   <family>Roboto Mono</family>
  </prefer>
 </alias>
</fontconfig>
```
Save, then run as root:

```
fc-cache -v -f
```
> - `binding="strong"` to forcely set
> - You can re-order by your personal preference. I like `DejaVu Sans Mono`

------

Or you can also overwrite the font-face containing italic by your self.
