### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by priyadarshan** [kuanyui/moe-theme.el#23]
I am sorry to open a ticket just to thank you, but I do not see how else I could do it.

I usually use a theme either because I like it, or because it enhance my productivity. This is the first time that I can actually use a theme that I like AND that enhance my productivity.
Beautiful theme, both versions of course.

Thank you so much for it!

**Comment by sakaki-** [comment]
+1 I use emacs all day, most days, and it makes a big difference to have such a nice theme
ありがとうございます ^-^
