### ISSUE TITLE
`(setq show-paren-style 'expression)` causes "Invalid Face" error

### ISSUE THREAD

**Issue by zilti** [kuanyui/moe-theme.el#45]
Using `(setq show-paren-style 'expression)` causes an error:

```emacs-lisp
Debugger entered--Lisp error: (error "Invalid face" rst-level-1-face)
  internal-set-lisp-face-attribute(rst-level-1-face :height 2.0 0)
  set-face-attribute(rst-level-1-face nil :height 2.0)
  moe-theme-resize-font-size()
  moe-dark()
  moe-theme-set-color(purple)
  eval((moe-theme-set-color (quote purple)) nil)
  eval-last-sexp-1(nil)
  eval-last-sexp(nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

**Comment by kuanyui** [comment]
Thank you, the problem exists should because the latest rst-mode changes its faces' names.
https://github.com/kuanyui/moe-theme.el/commit/601fd5839a298937a3535d67f62e481489e58e2d

If still not solved, have you ever try the settings under `emacs -Q` ?
```lisp
(show-paren-mode t)
(setq show-paren-style 'expression) 
```
Paste into *scratch* and M-x eval-buffer.

**Comment by zilti** [comment]
Yes, your commit solves the problem, perfect! I really like the theme by the way, and it's the first I've come across I like **and** that works in a shell, too!

**Comment by kuanyui** [comment]
Thanks for your using, I made this theme just because I always use Emacs under terminal ;)
