### ISSUE TITLE
support customized rainbow-identifiers faces

### ISSUE THREAD

**Issue by tanzoniteblack** [kuanyui/moe-theme.el#46]
Possible enhancement idea:

Support [rainbow-identifiers](https://github.com/Fanael/rainbow-identifiers#customization) faces by adding colored faces for `rainbow-identifiers-identifier-<number>` (by default, rainbow-identifiers identifies 1-14, but we can customize how many faces it should use with the variable `rainbow-identifiers-face-count`, but the higher the number, the more useful this mode is to people).

Example code that does the customization, which I'm not submitting as a merge request because I'm not great at making the actual color choices.
inside `custom-theme-set-faces`:

```emacs-lisp
   ;; rainbow-identifiers
   `(rainbow-identifiers-identifier-1 ((,class (:foreground ,red-2))))
   `(rainbow-identifiers-identifier-2 ((,class (:foreground ,blue-1))))
   `(rainbow-identifiers-identifier-3 ((,class (:foreground ,green-2))))
   `(rainbow-identifiers-identifier-4 ((,class (:foreground ,magenta-2))))
   `(rainbow-identifiers-identifier-5 ((,class (:foreground ,cyan-3))))
   `(rainbow-identifiers-identifier-6 ((,class (:foreground ,orange-2))))
   `(rainbow-identifiers-identifier-7 ((,class (:foreground ,purple-2))))
   `(rainbow-identifiers-identifier-8 ((,class (:foreground ,white-1))))
   `(rainbow-identifiers-identifier-9 ((,class (:foreground ,yellow-2))))
```

and inside `custom-theme-set-variables`:
```emacs-lisp
`(rainbow-identifiers-face-count 9)
```

**Comment by kuanyui** [comment]
Well...Just had a quickly try of this package, I have no idea at all about the color choices for it;...it makes my codes looks a terrible mess....(Especially for a high-contrasted color theme)

Therefore, I prefer let user set their faces for this mode, if she or he need.

BTW, thanks for your suggestion and contributions :)

**Comment by tanzoniteblack** [comment]
Thanks for at least looking into it, I couldn't come up with a good set of color choices for this theme either (though the defaults provided don't look *terrible*). Feel free to close the issue if you want then, or just label it as "minor enhancement" or something for one of us to look at again in the future.

**Comment by kuanyui** [comment]
I think I won't add faces for this mode.
By the way, a package `highlight-symbol` is a fabulous tool (and, at least for me, much more practical than `rainbow-identifiers`) for someone needs highlight identifiers when reading codes. Just a personal recommendation :-)
