### ISSUE TITLE
Resizing titles in the light theme does not work

### ISSUE THREAD

**Issue by joonro** [kuanyui/moe-theme.el#52]
Hi,

Thanks for the great theme. I'm using the following options to resize titles:

```elisp
(setq moe-theme-resize-markdown-title '(1.5 1.4 1.3 1.2 1.0 1.0))
(setq moe-theme-resize-org-title '(1.5 1.4 1.3 1.2 1.1 1.0 1.0 1.0 1.0))
(setq moe-theme-resize-rst-title '(1.5 1.4 1.3 1.2 1.1 1.0))
```

I found that with `(moe-light)`, resizing does not work, while it works fine with `(moe-dark)`. But when I eval `(moe-dark)` first, and then eval `(moe-light)`, then resizing is correctly applied.

**Comment by kuanyui** [comment]
I think it may be possible that you place these settings **before** `(moe-dark)` or `(moe-light)`. Because font resizing mechanism is applied when you run `(moe-dark)` or `(moe-light)`, so place your resizing settings before then.

**Comment by joonro** [comment]
That was it. Thank you so much for the quick reply. 

I think it might be a good idea to have that information in the documentation so it is clear.

**Comment by kuanyui** [comment]
Indeed, thanks for your feedback.

**Comment by vidjuheffex** [comment]
```
(use-package moe-theme
  :ensure t
  :init
  (setq moe-theme-resize-markdown-title '(1.5 1.4 1.3 1.2 1.0 1.0))
  (setq moe-theme-resize-org-title '(1.5 1.4 1.3 1.2 1.1 1.0 1.0 1.0 1.0))
  (setq moe-theme-resize-rst-title '(1.5 1.4 1.3 1.2 1.1 1.0))
  :config
  (load-theme 'moe-light 'no-confirm))
```

I'm having the same issue @kuanyui 
even if I move the code from the init block to above the load-theme call. I have to toggle dark-to-light to get it to work. any thoughts?

**Comment by kuanyui** [comment]
You should use (moe-light) instead of (load-theme THEME).

**Comment by vidjuheffex** [comment]
Thank you
