### ISSUE TITLE
bg color for rst-mode headings are too bright for moe-dark

### ISSUE THREAD

**Issue by joonro** [kuanyui/moe-theme.el#53]
Currently the background color for headings in `rst-mode` is too light in `moe-dark` and it is hard to read the heading title. 

![image](https://cloud.githubusercontent.com/assets/1063143/6435342/27482a9e-c062-11e4-87c5-9a8fe5587398.png)

**Comment by kuanyui** [comment]
Thanks for your reporting! This problem is due to lastest RST mode changed its faces names. Now fixed.

**Comment by joonro** [comment]
Thank you so much for your quick reply.
