### ISSUE TITLE
#+end_src too dark for moe-dark

### ISSUE THREAD

**Issue by joonro** [kuanyui/moe-theme.el#54]
Hi,

I just updated the `moe-theme` from melpa. I found one issue, which is that in `moe-dark`, the foreground color for `#+end_src` for code blocks in org-mode is very dark:

![image](https://cloud.githubusercontent.com/assets/1063143/6453943/6cea9a62-c109-11e4-8cdd-600639c8dc6d.png)

`#+end_src` is above `#+begin_src python :noweb-ref IGNORE` but you barely see it. Could you please fix this? Thank you so much!

**Comment by tanzoniteblack** [comment]
See comments on https://github.com/kuanyui/moe-theme.el/issues/40 about why the dark color was chosen

**Comment by kuanyui** [comment]
I'm curious about if anyone feel this face is a obstacle to using Org's block @@

**Comment by tanzoniteblack** [comment]
I'm completely indifferent to it.

**Comment by joonro** [comment]
I agree that making it have the same color as the `#+begin_src` would be an overkill. But currently it is just too dark - When I'm editing, I'm just not sure if there is `#end_src` or not. It has caused me to make mistakes (I guess it is different depending on the monitor settings as well). I think making it slightly lighter would surface.

**Comment by kuanyui** [comment]
When syntax for a block is valid, the block should has a highlighted background immediately. So it never be a question for me...

Like this screenshot, all blocks have a lighter background:
![](https://raw.githubusercontent.com/kuanyui/moe-theme.el/master/pics/dark01.png)

And maybe a tiny tip would be helpful for you: in Org-mode, just create a newline, enter `<s`  (or `<q`, `<h`, `<e` ...etc) then press `Tab`, it will expand to a source block automatically.

**Comment by joonro** [comment]
Thanks for the comment. 

I tend to lower the brightness of my monitors at night so it might be especially dark in my monitor. While I prefer to have it more visible, I guess it is just difference in preferences.

**Comment by kuanyui** [comment]
In fact, I set this face totally invisible at first because it's really useless at all when you editing  =w="

But you mean the background color looks insignificant in your monitor... Hmmm... #3a3a3a & #303030 in most monitors should be not difficult to distinguish ... Maybe try to adjust the contrast of your monitor?

Or... I think it should be well to add a var to config this.

**Comment by joonro** [comment]
No the background highlighting for source code block is fine.

When I opened this issue I was not aware that it was intentional, and I assumed that the dark `#+end_src` was a bug. But now I know it was intentional, maybe I will get used to it.  At first I was a bit worried about not being able to quickly see `#+end_src`, but as you said, as long as the background highlighting is correct, I don't have to worry about `#+end_src`. I do agree that it looks clean.

Thank you so much for your quick replies! I will report back if I face some problems because of this in the future.

**Comment by breadncup** [comment]
Would you add a var to config of this, please? It's too dark for me as well. I need to see where the "END" is located as well.

**Comment by kuanyui** [comment]
You needn't to see that string anyway. Just see where's the bottom of the gray background.

**Comment by breadncup** [comment]
Yeah, but if you give an option to a user to config it, it would be great as well. Or, like #+BEGIN_SRC, if there is a bar in the "END", it would be easier to look for me. It's personal preference, though.
