### ISSUE TITLE
Moe-light refine-hunk faces

### ISSUE THREAD

**Issue by tnielens** [kuanyui/moe-theme.el#57]
Moe-light refine-hunk faces are not contrasting enough with normal diff faces. It'd be great to improve that (diff-mode).

**Comment by kuanyui** [comment]
Can you give me a screenshot? I cannot get which face you are saying.

**Comment by tnielens** [comment]
![refinehunkhighcontrast](https://cloud.githubusercontent.com/assets/11885535/7493622/dd556f76-f402-11e4-87ad-a4c5d59fd5ca.PNG)
![refinehunklowcontrast](https://cloud.githubusercontent.com/assets/11885535/7493623/dd5773ca-f402-11e4-9502-beaa8ca83953.PNG)
With moe-light activated I get the result shown in the LowContrast screen shot. When I activate solarized-light theme before moe-light, I get the HighContrast screen shot (which is better I think).

**Comment by kuanyui** [comment]
Thank you for your reporting, now fixed :heart:

**Comment by tnielens** [comment]
Great ! Thank you
