### ISSUE TITLE
opened files color error in buffer when using helm with moe-theme-light

### ISSUE THREAD

**Issue by yanyingwang** [kuanyui/moe-theme.el#58]
Please get the point of this issue by view pictures attached below:

![light1](https://raw.githubusercontent.com/yanyingwang/notes/master/moe-theme/1.png)
![dark1](https://raw.githubusercontent.com/yanyingwang/notes/master/moe-theme/1d.png)

![light2](https://raw.githubusercontent.com/yanyingwang/notes/master/moe-theme/2.png)
![dark2](https://raw.githubusercontent.com/yanyingwang/notes/master/moe-theme/2d.png)

Also, please let me know if it's my emacs config problem.Thanks!

**Comment by kuanyui** [comment]
You mean the terrible orange & magenta on `size` and `path` fields of the buffers?
If yes, may I know what command you are using? My M-x `helm-buffers-list` has no problem like yours.

**Comment by yanyingwang** [comment]
Sorry, no, not `size` or `path` problem. I mean that  filename color of opened file is too white too be seen in my `helm-mini` and `helm-buffers-list` frame, which is perfect with moe dark theme.

![too-white](https://raw.githubusercontent.com/yanyingwang/notes/master/moe-theme/3.png)

![too-white](https://raw.githubusercontent.com/yanyingwang/notes/master/moe-theme/3d.png)

**Comment by kuanyui** [comment]
Hmmm... I cannot reproduce your screenshot, no matter on X & tty.
All action you've done is just `helm-buffers-list`, without any other theme enabled first?
![moetheme](https://cloud.githubusercontent.com/assets/1370070/7604090/323bd576-f970-11e4-8b8f-d77e2651c8f0.png)

**Comment by yanyingwang** [comment]
I'm very sorry, it's all my bad that turns out this odd and ugly color comes from another theme I loaded before moe-theme.
I'm very appreciate it to you that you waste time solving my problem. And by the way, gorgeous color theme for emacs you did!  I'm loving it!

![fixed](https://raw.githubusercontent.com/yanyingwang/notes/master/moe-theme/fixed.png)

**Comment by kuanyui** [comment]
Don't feel sorry because I've ever also reported issues like this =w="
