### ISSUE TITLE
Color of soft-wrapped linum

### ISSUE THREAD

**Issue by bryangarza** [kuanyui/moe-theme.el#60]
Hello

Does anyone know which face I need to set so that in the linum column, even the soft-wrapped lines are the same background? I haven't been able to find which font face it is. I want all the lighter squares in the line number column filled in.

Usually have no problem finding which font faces to edit but this one is stumping me, I can't check which one it is with <kbd>C-u C-x =</kbd> because it's not possible to place the cursor there.

![screen shot 2015-06-04 at 10 55 53 pm](https://cloud.githubusercontent.com/assets/1396101/8000257/14fad06c-0b0d-11e5-842b-b80ff5b47953.png)

**Comment by kuanyui** [comment]
So far as I know, it's impossible to customize the face at that place... If anyone knows, please let me know, or feel free and make a PR. Thanks.

**Comment by bryangarza** [comment]
I found [an answer in the Emacs StackExchange](http://emacs.stackexchange.com/a/897) that gives a solution, but it's not really that useful as it causes lag when scrolling in modes that use a lot of overlays (for example in org-mode). Here it is:

<hr>
### The Problem

The problem here is that there’s no face to control the appearance of the margins. You can display text in the margin using overlays (that’s what `linum-mode` does) but, like any text in Emacs, it’s constrained to the limits of the buffer. So you can’t have any control over the margin display beyond the last line of the buffer.

What you can do, is fix those faulty lines in-between. 

### What to put there

This variable controls what you want to display on those visual lines “between” two logical lines. The important part is the `'face 'linum`, which ensures these lines will follow the appearance of `linum-mode`. The `-----` part is demonstrative, you can change it to spaces or whatever you wish.

``` elisp
(defvar endless/margin-display
  `((margin left-margin) ,(propertize "-----" 'face 'linum))
  "String used on the margin.")
```

#### How to do it

The following code goes through the buffer and places overlays (similar to the ones linum-mode uses) on each line which isn’t “real”.

``` elisp
(defvar-local endless/margin-overlays nil
  "List of overlays in current buffer.")

(defun endless/setup-margin-overlays ()
  "Put overlays on each line which is visually wrapped."
  (interactive)
  (let ((ww (- (window-width)
               (if (= 0 (or (cdr fringe-mode) 1)) 1 0)))
        ov)
    (mapc #'delete-overlay endless/margin-overlays)
    (save-excursion
      (goto-char (point-min))
      (while (null (eobp))
        ;; On each logical line
        (forward-line 1)
        (save-excursion
          (forward-char -1)
          ;; Check if it has multiple visual lines.
          (while (>= (current-column) ww)
            (endles/make-overlay-at (point))
            (forward-char (- ww))))))))

(defun endles/make-overlay-at (p)
  "Create a margin overlay at position P."
  (push (make-overlay p (1+ p)) endless/margin-overlays)
  (overlay-put
   (car endless/margin-overlays) 'before-string
   (propertize " "  'display endless/margin-display)))
```

And we want to it run whenever linum-mode updates the line numbers.

``` elisp
(add-hook 'linum-before-numbering-hook #'endless/setup-margin-overlays)
```

![screen shot 2015-06-05 at 10 54 43 am](https://cloud.githubusercontent.com/assets/1396101/8011842/4eb1e94e-0b71-11e5-9be6-d20a9d626337.png)

<hr>

Gonna close this issue as it isn't moe related, it's just a limitation of Emacs.

Thanks for the great theme by the way  ◕ ◡ ◕

**Comment by xin-jin** [comment]
Did you try modifying the background color of the face `Linum`? Worked for me for another theme.
