### ISSUE TITLE
Hard to see function name when using CEDET and stickyfunc-mode

### ISSUE THREAD

**Issue by nyqvist** [kuanyui/moe-theme.el#62]
Hi,

I am using moe-light with CEDET and stickyfunc-mode enabled.
(add-to-list 'semantic-default-submodes 'global-semantic-stickyfunc-mode)

Background color for this sticky header is a little bit too dark.

![cedet_stickyfunc](https://cloud.githubusercontent.com/assets/1544300/8304730/f4bb5696-19a8-11e5-9e4d-2088a9091408.png)

**Comment by kuanyui** [comment]
Thanks for your reporting, the problem fixed and headers should look better now.

-------
(Just as a memento) Maybe the last time push commit via university's wifi. 2015/6/23 23:27 @ International Agriculture Center, NCHU.

**Comment by nyqvist** [comment]
Great, thanks!
