### ISSUE TITLE
Color of ggtags Project name on mode-line is too bright for active buffer

### ISSUE THREAD

**Issue by nyqvist** [kuanyui/moe-theme.el#63]
When using ggtags-mode it is hard to see the project name for ggtags on the mode-line (ggtags-mode-line-project-name) because the color is too bright for the active window. For the inactive one it is OK.

It seems that the face used for this is: compilation-info-face .

![moe-ggtags-mode-line_2015-07-25](https://cloud.githubusercontent.com/assets/1544300/8889837/20902368-32eb-11e5-9be3-12ca6e164d39.png)

**Comment by kuanyui** [comment]
Sorry for late to fix this. Thanks for your reporting!

**Comment by kuanyui** [comment]
Sorry, I forgot to fix my fix... Now it should be ok.
