### ISSUE TITLE
Incorrect background in fiplr

### ISSUE THREAD

**Issue by krzysztof-magosa** [kuanyui/moe-theme.el#64]
Hi,

I'm using fiplr, and background is incorrect.
Could it be fixed, please?

Cheers.

<img width="889" alt="screen shot 2015-09-07 at 11 15 09" src="https://cloud.githubusercontent.com/assets/6112411/9713560/7f7d5e34-5552-11e5-99e2-7b7595afde4c.png">

**Comment by kuanyui** [comment]
Thanks your reporting, but I don't know how to deal with this problem, even after roughly reading `fiplr`'s source code. Maybe you will want to try 'projectile'? It provides the same feature but without this issue.

**Comment by kuanyui** [comment]
If you still have question, please open the issue again. Thanks!

**Comment by krzysztof-magosa** [comment]
Switched to projectile, cheers!
