### ISSUE TITLE
Table render bug

### ISSUE THREAD

**Issue by lianxiangru** [kuanyui/moe-theme.el#69]
If I use code style in a table, it will look like this. The background after the code style is rendered to be the same as the background outside the table.

![screenshot from 2015-11-16 18-32-28](https://cloud.githubusercontent.com/assets/8991941/11198160/93817d00-8c90-11e5-9a0f-0ab63176b820.png)

**Comment by kuanyui** [comment]
Yes, I know this issue, but it should be a problem of Org-mode, not theme.

**Comment by kuanyui** [comment]
If you're willing to, maybe send a ticket to Org-mode's mailling list.

**Comment by kuanyui** [comment]
Btw, may I know how do you make the `=` or `~` invisible like that?

**Comment by lianxiangru** [comment]
@kuanyui 
ic. I've already opened an issue in org-mode repository. This is not a big problem though it is a little annoying to have that inconsistent background.

As for your question, try `(setq org-hide-emphasis-markers t)`.

**Comment by kuanyui** [comment]
Thank you! I love this setting!
