### ISSUE TITLE
web-mode syntax highlighting very dark in moe-dark

### ISSUE THREAD

**Issue by esjee** [kuanyui/moe-theme.el#70]
`moe-dark`:
![2016-02-01-212402_467x138_scrot](https://cloud.githubusercontent.com/assets/2501554/12730113/89876aea-c92a-11e5-947a-96ca6765921f.png)

`moe-light`:
![2016-02-01-212416_437x106_scrot](https://cloud.githubusercontent.com/assets/2501554/12730108/86e81492-c92a-11e5-92f3-9fa9c422eb6f.png)

The top one is hard to read. Do you know of any way to improve this?

**Comment by choma** [comment]
I'm not sure why, but I guess there is something wrong, it shouldn't look like that.
In first place, I see that your code has some errors (wrongly closed tags, div and h1), maybe fixing that improves something.
Besides that, is the example code an ember template? can you post the full file content so I can see how it look to me?

As an example here is what it look to me some ember code (route and template):
![captura de pantalla de 2016-02-01 17-53-51](https://cloud.githubusercontent.com/assets/4775453/12730908/e337424a-c90c-11e5-9663-695349f08913.png)

**Comment by esjee** [comment]
Thanks for pointing out the invalid tags, that wasn't intentional. Typing them in the dark wasn't a good idea. :)

Unfortunately, fixing the tags changes nothing. What you see in the screenshot is the entire file; it's an ERB template (`.html.erb`). After your comment, tried some other extensions.

`.html`:
![2016-02-01-221316_120x39_scrot](https://cloud.githubusercontent.com/assets/2501554/12731300/8dcf0486-c930-11e5-8db2-01916a01e0e7.png)

`.djhtml`:
![2016-02-01-221246_602x589_scrot](https://cloud.githubusercontent.com/assets/2501554/12731310/99c82254-c930-11e5-87ef-dc24ac2a5a31.png)

Also, I tried opening the file in GTK emacs; the syntax highlighting works as expected. Based on that, I think the most likely cause is (my own) terminal color config. Still not sure what the issue is, exactly, but it doesn't look like moe-theme is to blame.

Because I don't think it's moe-theme, I'll close this issue. Thanks for the help @choma.
