### ISSUE TITLE
Installing moe-theme changes the default font settings for emacs

### ISSUE THREAD

**Issue by Trevoke** [kuanyui/moe-theme.el#81]
``` emacs-lisp
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((((class color) (min-colors 4096)) (:foreground "#5f5f5f" :background "#fdfde7")) (((class color) (min-colors 256)) (:foreground "#5f5f5f" :background "#fdfde7")) (((class color) (min-colors 89)) (:foreground "#5f5f5f" :background "#fdfde7")))))
```

This was changed after installing moe-theme.

**Comment by kuanyui** [comment]
What did you mean?

**Comment by Trevoke** [comment]
I mean that after I installed moe-theme (through use-package), the custom
font settings for the default face for emacs were changed.

**Comment by thriveth** [comment]
I had the same problem. I cannot use moe-theme for this reason, which is a shame, because I like the design. But it messes up my init file.

**Comment by Trevoke** [comment]
Oh man, I'd forgotten about this.

@thriveth are you using `use-package` ? If so, try manually installing moe-theme and removing the `use-package` line from your init. See if the problem still happens?

**Comment by kuanyui** [comment]
@Trevoke @thriveth Sorry both, I don't sure if this issue resulted from a workaround for elder version Emacs. Is this issue still exist now?

**Comment by Trevoke** [comment]
Okay, I've confirmed that this problem only occurs for me if I'm using `use-package` to install themes, which is known to have a problem with themes: https://github.com/jwiegley/use-package/issues/351

Sorry for keeping this open so long, the issue is not with your package.
