### ISSUE TITLE
I think this package from package-install repository has an error?!

### ISSUE THREAD

**Issue by colorgmi** [kuanyui/moe-theme.el#83]
moe-theme-autoloads.el need one line code:

(and load-file-name (boundp 'custom-theme-load-path) (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))

;; I see other theme has this code, but not moe-theme
;; I personally like moe-light and mor-dark very much, thank you!

**Comment by kuanyui** [comment]
Oops, sorry I didn't notice this issue. :sob: 

moe-theme-autoloads.el need one line code:
```lisp
(and load-file-name (boundp 'custom-theme-load-path) (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))

;; I see other theme has this code, but not moe-theme
;; I personally like moe-light and mor-dark very much, thank you!
```
But I don't know where to place this... @@ sorry if any one could gives me a PR?
