### ISSUE TITLE
Atom support

### ISSUE THREAD

**Issue by enizor** [kuanyui/moe-theme.el#85]
I discovered this theme while trying out Emacs. It is just awesome, however Emacs did not convince me. That's why I would like to port this theme into an Atom theme. (4 actually: UI/syntax and light/dark).

As I never tried to create/customize themes it will take some time to translate , and confirmation from the Emacs user that it actually looks like the original theme (in particular for the different modes).

Let me know what you think!

**Comment by kuanyui** [comment]
In fact, I think the most important (and the most time-costing) part of moe-theme is the supporting for various modes -- the collocation of colors on their UI. I spent lots, lots of time on each supported mode (e.g. Magit) to feel how the whole UI looks with these colors selections. This is the reason why I never try to port moe-theme into other editor.
