### ISSUE TITLE
Xresources conversion

### ISSUE THREAD

**Issue by mrlinuxfish** [kuanyui/moe-theme.el#86]
I really like this theme and would like to theme the rest of my workstation with this theme. I can't quite figure out which hex value in the theme is related to the colors in Xresources for theming a terminal. Which colors in the theme should be copied to make a Xresources theme as similar to the moe dark theme?

**Comment by kuanyui** [comment]
Please search `font-lock-` in `moe-dark-theme.el`, that are the clues you need.

**Comment by mrlinuxfish** [comment]
Thanks. I got it sorted out.
