### ISSUE TITLE
semantic-decoration-on-unknown-includes face and file name is too similar

### ISSUE THREAD

**Issue by nyqvist** [kuanyui/moe-theme.el#95]
Hi,

I noticed that, in moe-light, the face: semantic-decoration-on-unknown-includes makes the header file name barely visible. You can see this if you enable global-semantic-decoration-mode

Screen shot:
![skarmbild_2018-09-18_09-03-08](https://user-images.githubusercontent.com/1544300/45687206-6c15a080-bb4e-11e8-948f-f3a81009bcb4.png)

**Comment by kuanyui** [comment]
https://github.com/kuanyui/moe-theme.el/commit/c36fbacfe5adf449c41ea265ced19273c22f4d49
Thanks for reporting. Now fixed in `dev` branch.
Currently I'm eating my dog food in `dev` for months, maybe you can try it is you wish.

**Comment by kuanyui** [comment]
Will fixed in 2.0
